### ISSUE TITLE
Expert / admin panel 

### ISSUE THREAD

**Issue by svinoczar** [svinoczar/web-project-itmoment#12]
- [x] Добавить в таблицу users столбец admin, принимающий значения от 0 до 1.
- [x] Сделать "панель эксперта" на сайте. 
- [x] Редирект в expert.php, либо открытие дополнительного окна (допуск к панели по кнопке в профиле) только при значении expert = 1 в users.

**Comment by jutsoNNN** [comment]
link на expert panel должна быть из profile.php?
=)

**Comment by svinoczar** [comment]
> link на expert panel должна быть из profile.php?
> =)

Da
